#' Mockup a Route
#' 
#' Creates a mockup of a route object. A mockup simulates what sort of response 
#' is generated by a route given a method, uri, and headers (optional).
#' 
#' @param r A \code{route} object.
#'   
#' @details
#' 
#' Unfortunately, \code{httpuv} requires a least one header is specified. 
#' Therefore, \code{headers} defaults to and must have at least one field 
#' specified.
#' 
#' @return
#' 
#' A route mockup will return the response object returned by the route handler.
#' However, if the method passed to the mockup is not handled by the route or if
#' the path is not handled by the route a 404 response object with a description
#' as the body is returned.
#' 
#' @export
#' @name mockup
#' @examples
#' logger <- route(
#'   'GET',
#'   '^',
#'   function(req) {
#'     print(req)
#'     response()
#'   }
#' )
#' 
#' logger_m <- mockup(logger)
#' logger_m('GET', '/yellow/brick/path')
#' logger_m('GET', '/phonday', headers = list(Accepts = 'text/html'))
mockup <- function(r) {
  if (!is.route(r)) stop('Cannot create mockup for class ', class(r)[1], call. = FALSE)

  m <- structure(
    function(method, uri, headers = list(`Content-Type` = 'text/plain')) {
      assert_that(
        is.character(method),
        length(method) == 1,
        is.character(uri),
        length(uri) == 1,
        length(headers) >= 1,
        is_named(headers)
      )

      e <- new.env(parent = baseenv())
      e$REQUEST_METHOD <- method
      split_on_query <- strsplit(uri, '?', fixed = TRUE)[[1]]
      e$PATH_INFO <- split_on_query[1]
      e$QUERY_STRING <- if (length(split_on_query) > 1) split_on_query[2] else ''
      lapply(names(headers), function(nm) assign(paste0('HTTP_', nm), headers[[nm]], envir = e))
      req <- as.request(e)

      if (is_match(r, req)) {
        res <- r$handler(req)

        if (!is.response(res)) {
          warning('handler returned object of class ', class(res), call. = FALSE)
        }
      } else {
        res <- response()
        status(res) <- 404
        body(res) <- paste0(
          'The method, uri combination could not be handled by the route.\n\n',
          '  route method  ', paste(r$method, collapse = ', '), ' (case-insensitive)\n',
          '    route path  "', r$path, '"\n\n',
          'request method  ', paste(req$method, collapse = ', '), '\n',
          '   request uri  "', r$uri, '"'
        )
      }

      invisible(res)
    },
    class = c('mockup', class(r))
  )

  attr(m, 'source') <- r

  m
}

#' @export
#' @rdname print.route
print.mockup <- function(x, ...) {
  print.route(attr(x, 'source', exact = TRUE))
}
